version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: 'all'
    default_reviewers:
      - 'kamaz'
    default_assignees:
      - 'kamaz'
    default_labels:
      - 'dependencies'
      - 'dependabot'
      - 'security'
    commit_message:
      prefix: 'chore'
      include_scope: true
